version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/sprintboot-test-api
    steps:
      # git pull
      - checkout

      - run:
          name: Decrpyt Secrets
          command: openssl enc -d -aes-256-ecb -md md5 -in src/main/resources/application-prod.properties.secrets -out src/main/resources/application-prod.properties -k $SECRETS_KEY

      - run:
          name: Running Integration Tests
          command: gradle test

      # Save test results for timing analysis
      - store_test_results:
          path: ~/sprintboot-test-api/test_results
      - store_artifacts:
          path: ~/sprintboot-test-api/test_results 

workflows:
  version: 2
  build_and_test:
#    triggers:
#      - schedule:
#          cron: "* 4 * * *"
#          filters:
#            branches:
#              only: master
    jobs:
      - build